# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  JadeEngine_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  JadeEngine_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  JadeEngine_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := JadeEngine Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

JadeEngine:
ifneq (,$(JadeEngine_config))
	@echo "==== Building JadeEngine ($(JadeEngine_config)) ===="
	@${MAKE} --no-print-directory -C JadeEngine -f Makefile config=$(JadeEngine_config)
endif

Sandbox: JadeEngine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C JadeEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   JadeEngine"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"